- README.md
- mathquill4quill.js
Issue #1 in this repository was about the formula editor not opening in safari. This PR fixes this issue by implementing the fix that was linked to in that issue. This is a fix, but it does sacrifice some functionality, mainly the fact that positioning the formula editor is not yet implemented on safari. 
This PR also adds in support for operator buttons, buttons that allow for users that are not familiar with latex to add in operators like square roots, fractions, and others. The method for adding in these buttons is by passing an array of arrays into the `enableMathQuillFormulaAuthoring()` function. This way of adding in operator buttons probably needs to be changed, but I did not know the best format to keep consistency with the rest of the project/Quill/MathQuill. The styling on these …
> Fixed bug in safari and added in support for operator buttons

- mathquill4quill.js
This pull request includes a restyling of the buttons to better match the styling of the quill editor's snow theme. Maybe integration with quill's theming in the future would be something to consider.
New Buttons:
Old Buttons:
This PR also contains a more complete fix for safari, changing around the CSS styling a little bit to make the tooltip display(I have no idea why this works). Maybe time for v0.0.2 if this gets merged.
> Updated styling on buttons and fixed safari positioning

- mathquill4quill.js
The operator buttons before this PR contain some interesting behavior where the operator buttons would not consistently placed vertically. This error occurred with `\frac`, and maybe others but I have not tested enough to find any others. This fixes issue #7 
Old Behavior:
New Behavior:
> Fixed positioning of operator buttons.

- README.md
- index.html
- mathquill4quill.js
This change adds a new top-level function `window.mathquill4quill` which acts as a factory method for the `enableMathQuillFormulaAuthoring` call. Decoupling the `enableMathQuillFormulaAuthoring` call from the Quill instance enables integrating the `mathquill4quill` library with other projects that are built on-top of Quill such as [react-quill](https://github.com/zenoamaro/react-quill) mentioned in https://github.com/c-w/mathquill4quill/issues/9.
> Add hook for integrating with react-quill

- mathquill4quill.js
- tests.js
This PR fixes issue #12, by making sure that the formula editor gets focused when it is opened. I had to use a `setTimeout()` to do this because otherwise the editor would not become visible(in Chrome at least). It would be nice if there is a better solution, but the current one works well, it is just not the most optimal.
> Autofocus formula editor when it is opened

- mathquill4quill.js
Set operator button type to button to prevent side effect where it triggers form submission.
> Prevent operator button from submitting a form

- azure-pipelines.yml
- package.json
The CI is currently failing ([see build](https://clewolff.visualstudio.com/mathquill4quill/_build/results?buildId=613)) due to a version mismatch between the latest Chrome and the version of `chromedriver` declared in `package.json`.
To fix the build and prevent future breakage, this pull request pins the version of Chrome used by the tests to version 78 which is available by default on the Ubuntu 18.04 Azure Pipelines agents ([see agent software list](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md)).
The pull request also updates the version of `release-it` to fix `npm audit` warnings.
> Fix chromedriver version mismatch

- package.json
The package published to NPM currently contains all the files in the repository which includes a bunch of unnecessary files (e.g. the code for the demo page).
This pull request makes the listing of files published to NPM explicit to include only:
- `mathquill4quill.js`: the core library written in ES6.
- `build/mathquill4quill.min.js`: a babelified and minified version of the file for older browsers.
> Add minified asset to npm package

- azure-pipelines.yml
This pull request uploads the nightwatch.js test results to Azure Pipelines for easier visualization and performance tracking.
Successful build:
Failed build:
> Publish test results to Azure Pipelines

- mathquill4quill.js
Currently the autofocus option can't be disabled since `options.autofocus || true` evaluates to true even if the option is explicitly set to false. Using the default value only if the provided value is null fixes the problem.
> Fix options.autofocus=false being discarded

- mathquill4quill.js
- package.json
- tests/editor.test.js
- tests/enter.test.js
- tests/math.test.js
The base Quill formula editor enables saving the formula by hitting the enter key. However, currently mathquill4quill swallows the enter key and requires manually clicking on the save button to finalize the formula (this is due to defaults in the MathQuill library).
This pull request fixes the behavior and enables saving the formula from mathquill4quill via the enter key.
Resolves https://github.com/c-w/mathquill4quill/issues/29
> Enable saving formula by hitting the enter key

- mathquill4quill.js
Resolves https://github.com/c-w/mathquill4quill/issues/33
> Preserve formula content when tooltip is closed

- .release-it.json
- .stylelintrc.js
- README.md
- index.html
- mathquill4quill.css
- mathquill4quill.js
- package.json
Resolves https://github.com/c-w/mathquill4quill/issues/35
> Make styles overridable

- package.json
Currently the intermediate babel output file (`build/mathquill4quill.js`) is being published to NPM although this file isn't useful for downstream consumers of the library. This change ensures that the file is removed from the build artifacts and not published to NPM.
> Remove intermediate babel output from build

- .release-it.json
This change fixes a regression introduced in https://github.com/c-w/mathquill4quill/pull/41 which broke publishing the non-minified version of `mathquill4quill.js` as a Github release artifact.
> Ensure non-minified JS is released as artifact

- .eslintrc.js
- .release-it.json
- .stylelintrc.js
- README.md
- index.html
- mathquill4quill.css
- mathquill4quill.js
- package.json
For some applications, it is helpful to re-use formula or edit formula. Currently, in Quill, this is tricky to implement. However, I've added some functionality to optionally display history of formulas which makes it easy to re-use and edit recent formula.
This works by saving formula to a list (and local storage). Then displaying this list when a user opens the formula tooltip.
Additionally, I noticed a small intentional bug from Quill where if the tooltip extends outside of the Quill div, the tooltip is moved up (in a very inconvenient spot in some cases). And this is more likely to happen as more content is added to the tooltip. The tooltip is only moved this way if the function button is clicked twice for some reason.
> Added support to display and save formula history.

- index.html
This change adds `displayHistory` (introduced in https://github.com/c-w/mathquill4quill/pull/40) to the [live demo page](https://justamouse.com/mathquill4quill/).
> Add demo for displayHistory option

- README.md
- mathquill4quill.js
- package.json
This pull request makes usage of `mathquill4quill` more ergonomic on modern stacks such as React by exposing the package as a module to enable `require` and `import` statements.
> Enable usage as a module

- package.json
Chrome got updated to version 87 in the Ubuntu 18.04 repositories, but Chromedriver hasn't been updated in this project to be compatible. This MR simply updates Chromedriver to version 87.
> Fixed pipeline fails

- mathquill4quill.js
- tests/commandOperatorButton.test.js
- tests/latexOperatorButton.test.js
I just realized that the original regex only allowed things like `\\sqrt[3]{}` but not `\\int_x^y`, so I just simplified the regex to detect \\ followed by just letters
> Improve command operator regex
